image: centos:7

stages:
    - deploy

before_script:
    - yum install which -y
    - 'which ssh-agent || ( yum install openssh-clients -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

production:
    stage: deploy
    script:
      - ssh -t ubuntu@ec2-52-74-15-84.ap-southeast-1.compute.amazonaws.com "cd test-nodejs-cicd && git checkout -f && git pull && npm install && pm2 stop ecosystem.config.js && pm2 start ecosystem.config.js"
    only:
      - master
    environment: production

develop:
    stage: deploy
    script:
      - ssh -t ubuntu@ec2-52-74-15-84.ap-southeast-1.compute.amazonaws.com "cd test-nodejs-cicd && git pull && git checkout -f &&  npm install && pm2 stop ecosystem.config.js && pm2 start ecosystem.config.js"
    only:
      - develop
    environment: develop
